# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0004_auto_20181014_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileup',
            name='file',
            field=models.FileField(upload_to='media/uploads/%Y/%m/%d/images'),
        ),
    ]
